# Kaggle ランクに基づいてバッジを自動生成するgithub action
# https://github.com/spider-man-tm/kaggle-badges/blob/main/docs/README.ja-jp.md

# github actionの設定ONにしないとこのファイルgit pushできなかった。以下のサイトのやり方で解決
# https://qiita.com/atsutama/items/10353f122fcb9f58c1d9

# git pushご手動でgithub action動かす必要あった
# GitHubリポジトリの「Actions」タブに移動し、「Kaggle Badges」ワークフローを選択し、「Run workflow」ボタンをクリックして手動でワークフローを実行必要だった

name: Kaggle Badges

on:
  push:
    branches:
      - main  # プッシュトリガー：main ブランチへのプッシュ時にも実行されます。
  schedule:
    # You can change the cron expression to suit your needs
    - cron: "11 11 1 * *" # 11:11 AM on the 1st of every month
  workflow_dispatch:  # 手動トリガー。GitHubリポジトリの「Actions」タブから手動で実行できます。

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome  # 最新のChromeをインストールする

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v1.2.3
        with:
          # ex. user_name: spidermandance
          user_name: anonamename
          # example of using GitHub Secrets
          # user_name: ${{ secrets.KAGGLE_USERNAME }}

      - name: Commit and Push SVG files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/* ./kaggle-plates/*
          git commit -m "Add generated SVG files" || echo "No changes to commit"
          git push